services:
  code-server: # Or dev_server_box, whatever you named it
    build:
      context: .
      args:
        HOST_DOCKER_GID: ${HOST_DOCKER_GID:-988}
    image: wn1980/dev-server-box
    container_name: dev_server_box
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - config:/home/ubuntu/.config
      - projects:/home/ubuntu/project
      - /var/run/docker.sock:/var/run/docker.sock
    ports: # <-- UNCOMMENTED and ensure it's 8443:8443
     - "8443:8443"
    restart: unless-stopped
    # user: "1000:1000" # Keep removed

# nginx: # <-- DELETE THIS ENTIRE BLOCK
#   image: nginx:stable-alpine
#   container_name: dev_server_box_nginx
#   ports:
#     - "8443:80"
#   volumes:
#     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#   restart: unless-stopped
#   depends_on:
#     - code-server

volumes:
  config:
  projects:

