# File: /home/developer/DEV/docker-code-server/docker-compose.yaml

# Create a .env file in this directory with the following content:
# HOST_DOCKER_GID=$(getent group docker | cut -d: -f3 || echo 999)
# (Replace 999 with a default GID if the docker group doesn't exist on your host)

services:
  dev-box:
    build:
      context: .
      args:
        HOST_DOCKER_GID: ${HOST_DOCKER_GID:-988} # Use default if not set
        ARCH: ${ARCH:-arm64} # Add ARCH build arg with default
    image: wn1980/dev-box:${ARCH:-arm64} # Set the custom image name and tag
    # Define the image name and tag.
    container_name: dev_box
    # privileged: true # Removed: Not needed for docker socket mount with correct GID
    # If specific capabilities are needed (e.g., for debugging), add them:
    # cap_add:
    #   - SYS_PTRACE # Example: For gdb debugging
    environment:
      - TZ=Asia/Bangkok
      - COMPOSE_BAKE=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=
      - EXTERNAL_FRONTEND_HOOKS_URLS=
    volumes:
      - config:/home/ubuntu/.config
      - conda:/home/ubuntu/.conda
      - n8n_data:/home/ubuntu/.n8n
      - Codespaces:/workspace
      # - projects:/home/ubuntu/projects
      # Mount the host Docker socket
      - /var/run/docker.sock:/var/run/docker.sock:ro # Added ':ro' for read-only mount - slightly safer
    ports:
     - "8443:8443"
    restart: unless-stopped
    # user: "1000:1000" # Keep removed - Container starts as root for supervisord

    # Optional: Add resource limits
    # Adjust these values based on your host machine and needs
    # mem_limit: 4g # Example: Limit memory usage to 4GB
    # cpus: '2.0'    # Example: Limit CPU usage to 2 cores

    # Optional: Add labels for organization
    labels:
      - "com.example.description=Code Server Development Environment"
      - "com.example.project=docker-code-server"

    healthcheck:
      # Test command assumes code-server runs HTTPS on 8443 and has /healthz
      # Adjust if your code-server setup is different (e.g., HTTP, different port/path)
      test: ["CMD", "curl", "-fk", "http://localhost:8443/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  config:
  conda:
  n8n_data:
    external: true
  Codespaces:
    external: true
