services:
  code-server:
    build: .
    image: wn1980/code-server-ai  # Added image tag
    container_name: code-server
    environment:
      - TZ=Asia/Bangkok # Timezone set previously
    volumes:
      - code-server-config:/home/ubuntu/.config/code-server
      - code-server-projects:/home/ubuntu/project
    ports:
      - "8443:8443"
    restart: unless-stopped
    user: "1000:1000"

volumes:
  code-server-config:
  code-server-projects: