services:
  code-server:
    build:
      context: .
      # args: # REMOVED this section
      #  HOST_DOCKER_GID: ${HOST_DOCKER_GID:-999}
    image: wn1980/dev-server-box
    container_name: dev_server_box
    environment:
      - TZ=Asia/Bangkok # Timezone set previously
    volumes:
      - config:/home/ubuntu/.config
      - projects:/home/ubuntu/project
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket mount
    ports:
      - "8443:8443"
    restart: unless-stopped
    # user: "1000:1000" # Keep this removed so supervisord starts as root

volumes:
  config:
  projects: